const ONE_MINUTE_IN_SECONDS = 60
const FIVE_MINUTES_IN_SECONDS = 300
const SIXTY_MINUTES_IN_SECONDS = 3600

module.exports = {
    ONE_MINUTE_IN_SECONDS,
    FIVE_MINUTES_IN_SECONDS,
    SIXTY_MINUTES_IN_SECONDS
}